# Generated by Django 4.0.5 on 2022-06-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0002_alter_formulario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
