# Generated by Django 4.0.5 on 2022-06-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0005_alter_formulario_asunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='asunto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='correo',
            field=models.CharField(max_length=50),
        ),
    ]
